version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/astrodb
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: bash -c "npm install && npm start"

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
